#!/bin/bash

    #Author : Utrains
    #Date : 24-October-2022

## ---------- script that installs docker -----------------        

echo "Docker to begin installation"

sudo yum install -y yum-utils
sudo yum-config-manager \
    --add-repo \
    https://download.docker.com/linux/centos/docker-ce.repo        
sudo yum install docker-ce docker-ce-cli containerd.io docker-compose-plugin

echo "Docker has been installed"
~                                                                  ~                                                                  ~                                      